### ISSUE TITLE
Where does rmsk=rmsk.bed.gz come from

### ISSUE THREAD

**Issue by algaebrown** [yangence/circfull#11]
Hi! Thanks for developing this package and answering questions in general.

I make my way to mRG step and when following the example, I wasn't able to figure out where `rmsk.bed.gz` is from?

**Comment by colinliuzelin** [comment]
Sorry for the confusion. It is an optional step to filter out circRNAs locating in repeat elements. You can download rmsk.bed.gz from UCSC genome browser (https://genome.ucsc.edu/cgi-bin/hgTables).
The format should like this:
chr1	67108753	67109046	L1P5	1892	+
chr1	8388315	8388618	AluY	2582	-
chr1	25165803	25166380	L1MB5	4085	+
chr1	33554185	33554483	AluSc	2285	-
chr1	41942894	41943205	AluY	2451	-
chr1	50331336	50332274	HAL1	1587	+

**Comment by algaebrown** [comment]
Hi Zelin,

Thanks for the timely reply :) Got it. So there are from the repeat masker?

**Comment by colinliuzelin** [comment]
Yes. They are from repeat masker.
