### ISSUE TITLE
How to detect Alternative Splicing events? 

### ISSUE THREAD

**Issue by gnilihzeux** [yangence/circfull#2]
Dear author,
      
Compared with other strategies like CIRI-long and isoCirc, yours has an improved power to detect Alternative Splicing events as mentioned in the article.

Could you please share your strategy that how to detect alternative splicing events ? There seems to be no clue in the paper. 

What I can think of is comparing circRNA exons model with known gene model. There is a schematic diagram of Exon Skipping below

```
Gene       -----------IIIIIIIIIIIIIIIIIIIII----------IIIIIIIIIIIIIIIIIIIII----------IIIIIIIIIIIIIIIIIIIIIIIII-------------
circRNA               IIIIIIIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIIIIIIIIII
```
But it's hard for me to achieve this especially for reads assignment to each exon.

So, is there any tool to implement this work, just like rMATS using in next-generation RNA-seq ?

Thanks a lot.

**Comment by colinliuzelin** [comment]
Hi,
Thank you for your question. The alternative splicing (AS) detection need at least two isoforms from one back-splicing junction. I directly used the circRNA position from BED file to calcuate AS events. I don't think reads alignment is  necessary for this alignment.  I'm not sure if there is any tool to implement this work. 
Best

**Comment by gnilihzeux** [comment]
Thank you for your reply.

Did you mean that we just need to classify SE/A5SS/A3SS/IR for transcripts derived from one back-splicing juction ?

**Comment by colinliuzelin** [comment]
Yes. My programming idea is to classify AS events for circRNA isoforms from same BSJ.

**Comment by gnilihzeux** [comment]
OK. Thanks for your sharing.
